import { createElement } from 'lwc';
import BlanketApp_BlanketManager from 'c/blanketApp_BlanketManager';

describe('c-blanket-app-blanket-manager', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-blanket-app-blanket-manager', {
            is: BlanketApp_BlanketManager
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});